feat: GraphModel added
rudderlabs/profiles-pycorelib pull request #10
Opened 2024-02-07 08:59 UTC by akankshar05

## Description of the change

 a new model added : GraphModel

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-02-07 10:31 UTC, shubhammehra4 commented on setup.py
> +        "profiles-rudderstack>=0.10.5, <=0.10.7, !=0.10.6",'pandas','matplotlib'
specify the version constraints for both the packages

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +    TypeName = "graph"
This is a very generic name but the implementation is very specific to the use case for reports. Improve the TypeName name

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/__init__.py
> +from .graph import GraphModel
Same here, very generic name

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        self.sql = ""
Remove sql from here

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        return self.sql, ".txt"
Fix describe to add some debug information for `pb compile`

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        self.logger.info("Preparing")
remove debug logs

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        output_folder=""
```suggestion
        output_folder = this.get_output_folder()
```

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +            else:
No need for the else block as we have continue in if block, either remove the else block or the continue statement. Also because we are using `this.de_ref()` and not `this.de_ref` with `edge_type="optional"` if `input_material` is `None` we should raise an exception.

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +                self.logger.info(
Remove all debugging logs

2024-02-07 10:31 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        df3=tables[2]
we are always expecting on 3 tables, not less or more but I don't see any constraints on the number of inputs, a very specific implementation but the model name and build_spec make it look like a generic implementation

2024-02-07 10:47 UTC, shubhammehra4 commented on src/profiles-pycorelib/graph.py
> +        threading.Thread(target=plot_graph, args=(output_folder, df1, df2, df3)).start()
Can you help me understand why we need a separate thread?

2024-02-08 08:41 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +import threading
Remove unnecessary imports

2024-02-08 09:11 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +    TypeName = "graph"
addressed.
TypeName changed to pyplot (as discussed).

2024-02-08 09:13 UTC, akankshar05 commented on src/profiles-pycorelib/__init__.py
> +from .graph import GraphModel
addressed. 
changed to 
=> pyplot and PyPlotModel

2024-02-08 09:16 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +        output_folder=""
addressed

2024-02-15 13:51 UTC, nishantsharma commented on README.md
> +      transformation: (x * 0.2 +5)
Shouldn't it be y?

2024-02-15 13:52 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        plotGraph(df_x[self.x_axis.get("column")], df_y[self.y_axis.get("column")], height,width ,self.x_axis.get("label"), self.y_axis.get("label"),output_folder, self.title, file_name,self.grid )
Break each param passed in separate line

2024-02-22 18:53 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +        return self.sql, ".txt"
addressed

2024-02-22 18:53 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +        self.logger.info("Preparing")
addressed.

2024-02-22 18:57 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +            else:
addressed.

2024-02-22 18:57 UTC, akankshar05 commented on src/profiles-pycorelib/graph.py
> +                self.logger.info(
addressed.

2024-02-22 18:57 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +import threading
removed.

2024-02-22 18:58 UTC, akankshar05 commented on README.md
> +      transformation: (x * 0.2 +5)
changed to y.

2024-02-22 19:46 UTC, akankshar05 commented on README.md
> +## This is how a GraphModel can be defined:
changed.

2024-02-22 19:46 UTC, akankshar05 commented on README.md
> +## This is how a PyPlotModel can be defined:
modified.

2024-02-24 07:09 UTC, shubhammehra4 requested changes

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +        if ("transformation" in self.x_axis) and self.x_axis.get("transformation"):
```suggestion
        if self.x_axis.get("transformation", False):
```

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +            elif isinstance(df_or_iterator, Iterator):
We can skip handling the Iterator case as Iterator is returned when we call `.get_df(batching=True)`

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +                raise InputMaterialNoneError("No data provided")
```suggestion
                raise MaterialNotFoundError(f"this.de_ref: unable to get material for {in_model}")
```

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +                self.logger.error("Transformation of X-axis values cannot be done as invalid transformation-expression")
Should we just log or raise an Exception?

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +        if ("transformation" in self.y_axis) and self.y_axis.get("transformation"):
```suggestion
        if self.y_axis.get("transformation", False):
```

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +class InputMaterialNoneError(Exception):
```suggestion
class MaterialNotFoundError(Exception):
```

2024-02-24 07:09 UTC, shubhammehra4 commented on src/profiles-pycorelib/pyplot.py
> +        description=this.name()+ "is created"
This could be misleading as we don't create the image in prepare

2024-02-25 20:51 UTC, nishantsharma commented on setup.py
> +        "profiles-rudderstack",'pandas>=1.4.3','matplotlib>=3.7.1', 'cexprtk'
We can specify the version we are testing for.

2024-02-25 20:52 UTC, nishantsharma commented on setup.py
> +        "profiles-rudderstack",'pandas>=1.4.3','matplotlib>=3.7.1', 'cexprtk'
And, versions we know for sure it would work with. Need guidelines here CC: @shubhammehra4

2024-02-29 14:14 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +        plotGraph(df_x[self.x_axis.get("column")], df_y[self.y_axis.get("column")], height,width ,self.x_axis.get("label"), self.y_axis.get("label"),output_folder, self.title, file_name,self.grid )
addressed.

2024-02-29 14:14 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +        if ("transformation" in self.x_axis) and self.x_axis.get("transformation"):
modified.

2024-02-29 14:14 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +            elif isinstance(df_or_iterator, Iterator):
skipped.

2024-02-29 14:15 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +                self.logger.error("Transformation of X-axis values cannot be done as invalid transformation-expression")
raised an exception

2024-02-29 14:15 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +        if ("transformation" in self.y_axis) and self.y_axis.get("transformation"):
addressed.

2024-02-29 14:15 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +class InputMaterialNoneError(Exception):
addressed.

2024-02-29 14:15 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +        description=this.name()+ "is created"
modified.

2024-03-19 08:07 UTC, nishantsharma commented on setup.py
> +        f"profiles-rudderstack=={limit_major_minor_version(version)}",'pandas>=1.4.3','matplotlib>=3.7.1', 'cexprtk==0.4.1'
This is confusing. Maybe, profiles version should be explicit.

2024-03-19 08:07 UTC, nishantsharma commented on setup.py
> +        f"profiles-rudderstack=={limit_major_minor_version(version)}",'pandas>=1.4.3','matplotlib>=3.7.1', 'cexprtk==0.4.1'
Which version would include support for our changes.

2024-03-19 08:12 UTC, nishantsharma commented on setup.py
> +        f"profiles-rudderstack=={limit_major_minor_version(version)}",'pandas>=1.4.3','matplotlib>=3.7.1', 'cexprtk==0.4.1'
Ensure that [1061](https://github.com/rudderlabs/wht/pull/1061/files) is released, before we merge this PR. Explicitly write the minimum supported version in line 31, at that time

2024-04-10 17:32 UTC, shubhammehra4 requested changes
We should not target main.

2024-04-10 18:11 UTC, nishantsharma commented
> We should not target main.

As discussed, targeting main is ok.

2024-04-17 03:43 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        print(self.build_spec.get("y_axis"))
Debug messages should be routed via logger. Else, we can be keep them commented.

2024-04-17 03:43 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        print(y_axis)
Debug messages should be routed via logger, or kept commented.

2024-04-17 03:44 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        print(y_axis)
Everywhere

2024-04-17 04:31 UTC, akankshar05 commented on src/profiles-pycorelib/pyplot.py
> +        print(y_axis)
removed. added by mistake.

2024-04-22 07:21 UTC, nishantsharma commented on setup.py
> +        f"profiles-rudderstack==0.11.3", 'pandas>=1.4.3', 'matplotlib>=3.7.1', 'cexprtk==0.4.1'
Let us release with 0.12.0. So, put >=0.12.0 here.

2024-04-22 07:22 UTC, nishantsharma approved these changes
LGTM. except for 1 comment.

2024-04-29 05:49 UTC, shubhammehra4 commented on setup.py
> +        f"profiles-rudderstack==0.11.3", 'pandas>=1.4.3', 'matplotlib>=3.7.1', 'cexprtk==0.4.1'
```suggestion
        f"profiles-rudderstack=={limit_major_minor_version(version)}", 'pandas>=1.4.3', 'matplotlib>=3.7.1', 'cexprtk==0.4.1'
```

The `version` is set to 0.12.0, so we don't need to change this.

2024-04-29 07:24 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        self.message = message
Move these two in errors.py

2024-04-29 07:24 UTC, nishantsharma commented on src/profiles-pycorelib/pyplot.py
> +        super().__init__(self.message)
Move these two in errors.py

2024-04-29 07:25 UTC, nishantsharma approved these changes
LGTM. Except for 1 comment.

2024-04-29 07:40 UTC, shubhammehra4 approved these changes

2024-04-29 07:41 UTC, merged