generating interactive figures for attribution
rudderlabs/profiles-pycorelib pull request #26
Opened 2024-05-15 11:14 UTC by joker2411

## Description of the change

> updated the heatmap generated for markov model transition probabilities into an interactive figure as .html file. Ticket [Link](https://linear.app/rudderstack/issue/PRML-567/update-attribution-output-heatmap-image).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-05-17 05:24 UTC, dpatchigolla requested changes
minor suggestions on renaming

2024-05-17 05:24 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +            "enable_visualisation": { "type": "boolean" },
Can we set up the default from here itself, in the spec?

2024-05-17 05:24 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +                          title="Markov model transition probabilities"):
The title is no longer correct. Can you modify to "User journey map"

2024-05-17 05:24 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +                print("Too many touchpoints to visualise. Please use final attribution score table to visualize results.")
This should be self.logger.info, not in print.

2024-05-17 05:24 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +                print("Too many touchpoints to visualise. Please use final attribution score table to visualize results.")
Too many touchpoints to visualise. Please use final attribution score table to visualize results >

Skipping visualising the attribution model outputs as there are too many touchpoints. Visualisation is supported only when we have fewer than {MAXIMUM....} touchpoints

2024-05-20 08:01 UTC, joker2411 commented on src/profiles-pycorelib/attribution_model.py
> +            "enable_visualisation": { "type": "boolean" },
not available rn.

2024-05-20 08:06 UTC, dpatchigolla approved these changes

2024-05-20 08:06 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +        if attribution_scores.shape[0] > MAXIMUM_TOUCHPOINTS_TO_VISUALIZE:
Can you add `enable_visualisation` too in the check? So 
`if enable_visualisation and attribution_scores.shape[0] > MAXIMUM_TOUCHPOINTS_TO_VISUALIZE:`

This way, we don't print a log message saying we are skipping visualisation if the flag is already False.

2024-05-20 15:09 UTC, merged