implementing matmul with scipy
rudderlabs/profiles-pycorelib pull request #32
Opened 2024-06-07 11:15 UTC by joker2411

## Description of the change

> the converge method was using numpy functions. This is very inefficient at large scale. We created a branch using torch to resolve this. But this similar functionality can be achieved through scipy, as scipy is a lot more generic than torch. Ticket [Link](https://linear.app/rudderstack/issue/PRML-648/move-attribution-model-to-scipylinalg).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-06-07 11:22 UTC, shubhammehra4 approved these changes

2024-06-10 10:26 UTC, dpatchigolla requested changes

2024-06-10 10:26 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +    def _converge(self, transition_matrix, max_iters=40, verbose=True):
Can you make verbose=False here

2024-06-10 10:26 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +                drop_transition_converged = self._converge(drop_transition, max_iters=500, verbose=False)
Can you remove the max_iters and verbose params here, and let the defaults be used? We don't need 500 iterations.

2024-06-10 10:26 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +        converged_transition_probabilities = self._converge(transition_probabilities, max_iters=500, verbose=False)
Same as above. No need of the default params.

2024-06-10 10:26 UTC, dpatchigolla commented on src/profiles-pycorelib/attribution_model.py
> +        self.logger = Logger("multitouch_models") # create a logger for debug/error logging
You can pass the same `attribution_model` logger from AttributionLogger class in init and use that.

2024-06-10 11:23 UTC, dpatchigolla approved these changes

2024-06-10 12:13 UTC, merged